/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author iGimenezSan
 */
public class FicheroEquipos extends javax.swing.JDialog {

    /**
     * Creates new form FicheroEquipos
     */
    public FicheroEquipos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalVentana_FicheroEquipos = new javax.swing.JPanel();
        panelBanner_FicheroEquipos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDatosEquipo_FicheroEquipos = new javax.swing.JPanel();
        labelTipoEquipo_FicheroEquipos = new javax.swing.JLabel();
        textboxTipoEquipo_FicheroEquipos = new javax.swing.JTextField();
        labelMarca_FicheroEquipos = new javax.swing.JLabel();
        textboxMarca_FicheroEquipos = new javax.swing.JTextField();
        labelModelo_FicheroEquipos = new javax.swing.JLabel();
        textboxModelo_FicheroEquipos = new javax.swing.JTextField();
        labelSerialEquipo_FicheroEquipos = new javax.swing.JLabel();
        textboxSerialEquipo_FicheroEquipos = new javax.swing.JTextField();
        labelSistema_FicheroEquipos = new javax.swing.JLabel();
        textboxSistema_FicheroEquipos = new javax.swing.JTextField();
        labelSerialSistema_FicheroEquipos = new javax.swing.JLabel();
        textboxSerialSistema_FicheroEquipos = new javax.swing.JTextField();
        labelPropietario_FicheroEquipos = new javax.swing.JLabel();
        textboxPropietario_FicheroEquipos = new javax.swing.JTextField();
        botonAsignarCliente_FicheroEquipos = new javax.swing.JButton();
        panelControl_FicheroEquipos = new javax.swing.JPanel();
        BotonNuevoEquipo_FicheroEquipos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        panelPrincipalVentana_FicheroEquipos.setMaximumSize(new java.awt.Dimension(800, 600));
        panelPrincipalVentana_FicheroEquipos.setMinimumSize(new java.awt.Dimension(800, 600));

        panelBanner_FicheroEquipos.setBackground(new java.awt.Color(255, 204, 204));
        panelBanner_FicheroEquipos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Gestión de Equipos");

        javax.swing.GroupLayout panelBanner_FicheroEquiposLayout = new javax.swing.GroupLayout(panelBanner_FicheroEquipos);
        panelBanner_FicheroEquipos.setLayout(panelBanner_FicheroEquiposLayout);
        panelBanner_FicheroEquiposLayout.setHorizontalGroup(
            panelBanner_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBanner_FicheroEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        panelBanner_FicheroEquiposLayout.setVerticalGroup(
            panelBanner_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBanner_FicheroEquiposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );

        panelDatosEquipo_FicheroEquipos.setBackground(new java.awt.Color(153, 153, 255));
        panelDatosEquipo_FicheroEquipos.setMaximumSize(new java.awt.Dimension(32767, 600));
        panelDatosEquipo_FicheroEquipos.setPreferredSize(new java.awt.Dimension(800, 118));

        labelTipoEquipo_FicheroEquipos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelTipoEquipo_FicheroEquipos.setText("Tipo de Equipo");

        textboxTipoEquipo_FicheroEquipos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textboxTipoEquipo_FicheroEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxTipoEquipo_FicheroEquiposActionPerformed(evt);
            }
        });

        labelMarca_FicheroEquipos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelMarca_FicheroEquipos.setText("Marca");

        textboxMarca_FicheroEquipos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textboxMarca_FicheroEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxMarca_FicheroEquiposActionPerformed(evt);
            }
        });

        labelModelo_FicheroEquipos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelModelo_FicheroEquipos.setText("Modelo");

        textboxModelo_FicheroEquipos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelSerialEquipo_FicheroEquipos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelSerialEquipo_FicheroEquipos.setText("Serial Equipo");

        textboxSerialEquipo_FicheroEquipos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textboxSerialEquipo_FicheroEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxSerialEquipo_FicheroEquiposActionPerformed(evt);
            }
        });

        labelSistema_FicheroEquipos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelSistema_FicheroEquipos.setText("Sistema Operativo");

        textboxSistema_FicheroEquipos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelSerialSistema_FicheroEquipos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelSerialSistema_FicheroEquipos.setText("Serial Sistema");

        textboxSerialSistema_FicheroEquipos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelPropietario_FicheroEquipos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelPropietario_FicheroEquipos.setText("NIF Propietario/a");

        botonAsignarCliente_FicheroEquipos.setText("Asignar Cliente");
        botonAsignarCliente_FicheroEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarCliente_FicheroEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosEquipo_FicheroEquiposLayout = new javax.swing.GroupLayout(panelDatosEquipo_FicheroEquipos);
        panelDatosEquipo_FicheroEquipos.setLayout(panelDatosEquipo_FicheroEquiposLayout);
        panelDatosEquipo_FicheroEquiposLayout.setHorizontalGroup(
            panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosEquipo_FicheroEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelMarca_FicheroEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelModelo_FicheroEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSerialEquipo_FicheroEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSistema_FicheroEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSerialSistema_FicheroEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTipoEquipo_FicheroEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelPropietario_FicheroEquipos))
                .addGap(18, 18, 18)
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textboxMarca_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textboxTipoEquipo_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textboxSistema_FicheroEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(textboxSerialEquipo_FicheroEquipos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textboxModelo_FicheroEquipos, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(textboxSerialSistema_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDatosEquipo_FicheroEquiposLayout.createSequentialGroup()
                        .addComponent(textboxPropietario_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAsignarCliente_FicheroEquipos)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelDatosEquipo_FicheroEquiposLayout.setVerticalGroup(
            panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosEquipo_FicheroEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoEquipo_FicheroEquipos)
                    .addComponent(textboxTipoEquipo_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMarca_FicheroEquipos)
                    .addComponent(textboxMarca_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelo_FicheroEquipos)
                    .addComponent(textboxModelo_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSerialEquipo_FicheroEquipos)
                    .addComponent(textboxSerialEquipo_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSistema_FicheroEquipos)
                    .addComponent(textboxSistema_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSerialSistema_FicheroEquipos)
                    .addComponent(textboxSerialSistema_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textboxPropietario_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPropietario_FicheroEquipos)
                    .addComponent(botonAsignarCliente_FicheroEquipos))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        BotonNuevoEquipo_FicheroEquipos.setText("Nuevo Equipo");
        BotonNuevoEquipo_FicheroEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoEquipo_FicheroEquiposActionPerformed(evt);
            }
        });

        jButton2.setText("Grabar Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControl_FicheroEquiposLayout = new javax.swing.GroupLayout(panelControl_FicheroEquipos);
        panelControl_FicheroEquipos.setLayout(panelControl_FicheroEquiposLayout);
        panelControl_FicheroEquiposLayout.setHorizontalGroup(
            panelControl_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControl_FicheroEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonNuevoEquipo_FicheroEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelControl_FicheroEquiposLayout.setVerticalGroup(
            panelControl_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControl_FicheroEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControl_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevoEquipo_FicheroEquipos)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalVentana_FicheroEquiposLayout = new javax.swing.GroupLayout(panelPrincipalVentana_FicheroEquipos);
        panelPrincipalVentana_FicheroEquipos.setLayout(panelPrincipalVentana_FicheroEquiposLayout);
        panelPrincipalVentana_FicheroEquiposLayout.setHorizontalGroup(
            panelPrincipalVentana_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalVentana_FicheroEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalVentana_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBanner_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalVentana_FicheroEquiposLayout.createSequentialGroup()
                        .addComponent(panelDatosEquipo_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelControl_FicheroEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelPrincipalVentana_FicheroEquiposLayout.setVerticalGroup(
            panelPrincipalVentana_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalVentana_FicheroEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBanner_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalVentana_FicheroEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDatosEquipo_FicheroEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(panelControl_FicheroEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelPrincipalVentana_FicheroEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipalVentana_FicheroEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textboxTipoEquipo_FicheroEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxTipoEquipo_FicheroEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxTipoEquipo_FicheroEquiposActionPerformed

    private void textboxMarca_FicheroEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxMarca_FicheroEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxMarca_FicheroEquiposActionPerformed

    private void textboxSerialEquipo_FicheroEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxSerialEquipo_FicheroEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxSerialEquipo_FicheroEquiposActionPerformed

    private void BotonNuevoEquipo_FicheroEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoEquipo_FicheroEquiposActionPerformed
        limpiarCamposFichaEquipo();
    }//GEN-LAST:event_BotonNuevoEquipo_FicheroEquiposActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonAsignarCliente_FicheroEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarCliente_FicheroEquiposActionPerformed
        FicheroClientes ventana = new FicheroClientes(null, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_botonAsignarCliente_FicheroEquiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheroEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FicheroEquipos dialog = new FicheroEquipos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNuevoEquipo_FicheroEquipos;
    private javax.swing.JButton botonAsignarCliente_FicheroEquipos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelMarca_FicheroEquipos;
    private javax.swing.JLabel labelModelo_FicheroEquipos;
    private javax.swing.JLabel labelPropietario_FicheroEquipos;
    private javax.swing.JLabel labelSerialEquipo_FicheroEquipos;
    private javax.swing.JLabel labelSerialSistema_FicheroEquipos;
    private javax.swing.JLabel labelSistema_FicheroEquipos;
    private javax.swing.JLabel labelTipoEquipo_FicheroEquipos;
    private javax.swing.JPanel panelBanner_FicheroEquipos;
    private javax.swing.JPanel panelControl_FicheroEquipos;
    private javax.swing.JPanel panelDatosEquipo_FicheroEquipos;
    private javax.swing.JPanel panelPrincipalVentana_FicheroEquipos;
    private javax.swing.JTextField textboxMarca_FicheroEquipos;
    private javax.swing.JTextField textboxModelo_FicheroEquipos;
    private javax.swing.JTextField textboxPropietario_FicheroEquipos;
    private javax.swing.JTextField textboxSerialEquipo_FicheroEquipos;
    private javax.swing.JTextField textboxSerialSistema_FicheroEquipos;
    private javax.swing.JTextField textboxSistema_FicheroEquipos;
    private javax.swing.JTextField textboxTipoEquipo_FicheroEquipos;
    // End of variables declaration//GEN-END:variables

    private void limpiarCamposFichaEquipo() {
        textboxMarca_FicheroEquipos.setText(null);
        textboxModelo_FicheroEquipos.setText(null);
        textboxSerialEquipo_FicheroEquipos.setText(null);
        textboxSerialSistema_FicheroEquipos.setText(null);
        textboxSistema_FicheroEquipos.setText(null);
        textboxTipoEquipo_FicheroEquipos.setText(null);
        textboxPropietario_FicheroEquipos.setText(null);
        
    }
}
