/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Objetos.ObjetoCliente;
import Toolbox.Conectores;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author iGimenezSan
 */
public class FicheroClientes extends javax.swing.JDialog {

    public static Conectores CONECTORES = new Conectores();
    /**
     * Creates new form FicheroClientes
     * @param parent
     * @param modal
     */
    public FicheroClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalVentana_FicheroClientes = new javax.swing.JPanel();
        panelBanner_FicheroClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDatosCliente_FicheroClientes = new javax.swing.JPanel();
        labelNIF_GestionCliente = new javax.swing.JLabel();
        textboxNIF_GestionClientes = new javax.swing.JTextField();
        labelNombre_GestionClientes = new javax.swing.JLabel();
        textboxNombre_GestionClientes = new javax.swing.JTextField();
        labelApellidos_GestionClientes = new javax.swing.JLabel();
        textboxApellidos_GestionClientes = new javax.swing.JTextField();
        labelDireccion_GestionClientes = new javax.swing.JLabel();
        textboxDireccion_GestionClientes = new javax.swing.JTextField();
        labelCodigoPostal_GestionClientes = new javax.swing.JLabel();
        textboxCodPostal_GestionClientes = new javax.swing.JTextField();
        labelPoblacion_GestionClientes = new javax.swing.JLabel();
        textboxPoblacion_GestionClientes = new javax.swing.JTextField();
        labelProvincia_GestionClientes = new javax.swing.JLabel();
        textboxProvincia_GestionClientes = new javax.swing.JTextField();
        labelTelefono_GestionClientes = new javax.swing.JLabel();
        textboxTelefono_GestionClientes = new javax.swing.JTextField();
        labelEmail_GestionClientes = new javax.swing.JLabel();
        textboxEmail_GestionClientes = new javax.swing.JTextField();
        panelControl_FicheroClientes = new javax.swing.JPanel();
        botonNuevoCliente_GestionClientes = new javax.swing.JButton();
        botonGrabarCliente = new javax.swing.JButton();
        botonConsultarRegistros_FicheroClientes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaResultados_FicheroClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        panelPrincipalVentana_FicheroClientes.setMaximumSize(new java.awt.Dimension(800, 600));
        panelPrincipalVentana_FicheroClientes.setMinimumSize(new java.awt.Dimension(800, 600));

        panelBanner_FicheroClientes.setBackground(new java.awt.Color(255, 204, 204));
        panelBanner_FicheroClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Gestión de Clientes");

        javax.swing.GroupLayout panelBanner_FicheroClientesLayout = new javax.swing.GroupLayout(panelBanner_FicheroClientes);
        panelBanner_FicheroClientes.setLayout(panelBanner_FicheroClientesLayout);
        panelBanner_FicheroClientesLayout.setHorizontalGroup(
            panelBanner_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBanner_FicheroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        panelBanner_FicheroClientesLayout.setVerticalGroup(
            panelBanner_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBanner_FicheroClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );

        panelDatosCliente_FicheroClientes.setBackground(new java.awt.Color(153, 255, 153));
        panelDatosCliente_FicheroClientes.setMaximumSize(new java.awt.Dimension(32767, 600));
        panelDatosCliente_FicheroClientes.setPreferredSize(new java.awt.Dimension(800, 118));

        labelNIF_GestionCliente.setText("NIF");

        textboxNIF_GestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxNIF_GestionClientesActionPerformed(evt);
            }
        });

        labelNombre_GestionClientes.setText("Nombre");

        textboxNombre_GestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxNombre_GestionClientesActionPerformed(evt);
            }
        });

        labelApellidos_GestionClientes.setText("Apellidos");

        labelDireccion_GestionClientes.setText("Dirección");

        textboxDireccion_GestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxDireccion_GestionClientesActionPerformed(evt);
            }
        });

        labelCodigoPostal_GestionClientes.setText("C.Postal");

        labelPoblacion_GestionClientes.setText("Población");

        labelProvincia_GestionClientes.setText("Provincia");

        labelTelefono_GestionClientes.setText("Teléfono");

        labelEmail_GestionClientes.setText("Correo Electrónico");

        javax.swing.GroupLayout panelDatosCliente_FicheroClientesLayout = new javax.swing.GroupLayout(panelDatosCliente_FicheroClientes);
        panelDatosCliente_FicheroClientes.setLayout(panelDatosCliente_FicheroClientesLayout);
        panelDatosCliente_FicheroClientesLayout.setHorizontalGroup(
            panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosCliente_FicheroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosCliente_FicheroClientesLayout.createSequentialGroup()
                        .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelEmail_GestionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(labelTelefono_GestionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textboxTelefono_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textboxEmail_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDatosCliente_FicheroClientesLayout.createSequentialGroup()
                        .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelNombre_GestionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelApellidos_GestionClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDireccion_GestionClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCodigoPostal_GestionClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPoblacion_GestionClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(labelProvincia_GestionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNIF_GestionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textboxNombre_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textboxNIF_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textboxApellidos_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textboxDireccion_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textboxCodPostal_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textboxPoblacion_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textboxProvincia_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelDatosCliente_FicheroClientesLayout.setVerticalGroup(
            panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosCliente_FicheroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNIF_GestionCliente)
                    .addComponent(textboxNIF_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre_GestionClientes)
                    .addComponent(textboxNombre_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidos_GestionClientes)
                    .addComponent(textboxApellidos_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccion_GestionClientes)
                    .addComponent(textboxDireccion_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoPostal_GestionClientes)
                    .addComponent(textboxCodPostal_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPoblacion_GestionClientes)
                    .addComponent(textboxPoblacion_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProvincia_GestionClientes)
                    .addComponent(textboxProvincia_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefono_GestionClientes)
                    .addComponent(textboxTelefono_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail_GestionClientes)
                    .addComponent(textboxEmail_GestionClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonNuevoCliente_GestionClientes.setText("Nuevo Cliente");
        botonNuevoCliente_GestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoCliente_GestionClientesActionPerformed(evt);
            }
        });

        botonGrabarCliente.setText("Grabar Cliente en BBDD");
        botonGrabarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarClienteActionPerformed(evt);
            }
        });

        botonConsultarRegistros_FicheroClientes.setText("Consultar Registros");
        botonConsultarRegistros_FicheroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarRegistros_FicheroClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControl_FicheroClientesLayout = new javax.swing.GroupLayout(panelControl_FicheroClientes);
        panelControl_FicheroClientes.setLayout(panelControl_FicheroClientesLayout);
        panelControl_FicheroClientesLayout.setHorizontalGroup(
            panelControl_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControl_FicheroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControl_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonConsultarRegistros_FicheroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonNuevoCliente_GestionClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(botonGrabarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelControl_FicheroClientesLayout.setVerticalGroup(
            panelControl_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControl_FicheroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControl_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevoCliente_GestionClientes)
                    .addComponent(botonGrabarCliente))
                .addGap(31, 31, 31)
                .addComponent(botonConsultarRegistros_FicheroClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalVentana_FicheroClientesLayout = new javax.swing.GroupLayout(panelPrincipalVentana_FicheroClientes);
        panelPrincipalVentana_FicheroClientes.setLayout(panelPrincipalVentana_FicheroClientesLayout);
        panelPrincipalVentana_FicheroClientesLayout.setHorizontalGroup(
            panelPrincipalVentana_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalVentana_FicheroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalVentana_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelBanner_FicheroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalVentana_FicheroClientesLayout.createSequentialGroup()
                        .addComponent(panelDatosCliente_FicheroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelControl_FicheroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelPrincipalVentana_FicheroClientesLayout.setVerticalGroup(
            panelPrincipalVentana_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalVentana_FicheroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBanner_FicheroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalVentana_FicheroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelControl_FicheroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosCliente_FicheroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaResultados_FicheroClientes.setAutoCreateRowSorter(true);
        tablaResultados_FicheroClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIF", "Nombre", "Apellidos", "Domicilio", "Codigo_Postal", "Poblacion", "Provincia", "Telefono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaResultados_FicheroClientes.setCellSelectionEnabled(false);
        tablaResultados_FicheroClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaResultados_FicheroClientes.setRowSelectionAllowed(true);
        tablaResultados_FicheroClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaResultados_FicheroClientes.getTableHeader().setReorderingAllowed(false);
        tablaResultados_FicheroClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaResultados_FicheroClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaResultados_FicheroClientes);
        tablaResultados_FicheroClientes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipalVentana_FicheroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelPrincipalVentana_FicheroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 251, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(355, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textboxNIF_GestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxNIF_GestionClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxNIF_GestionClientesActionPerformed

    private void textboxNombre_GestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxNombre_GestionClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxNombre_GestionClientesActionPerformed

    private void textboxDireccion_GestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxDireccion_GestionClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxDireccion_GestionClientesActionPerformed

    private void botonNuevoCliente_GestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoCliente_GestionClientesActionPerformed
        limpiarCamposFichaClientes();
    }//GEN-LAST:event_botonNuevoCliente_GestionClientesActionPerformed

    private void botonGrabarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarClienteActionPerformed
        ObjetoCliente datosCliente = new ObjetoCliente(textboxNIF_GestionClientes.getText(), textboxNombre_GestionClientes.getText(), textboxApellidos_GestionClientes.getText(), textboxDireccion_GestionClientes.getText(), textboxCodPostal_GestionClientes.getText(), textboxPoblacion_GestionClientes.getText(), textboxProvincia_GestionClientes.getText(), textboxTelefono_GestionClientes.getText(), textboxEmail_GestionClientes.getText());
        CONECTORES.insertarCliente(datosCliente);
        JOptionPane.showMessageDialog(null, "Cliente registado correctamente");
    }//GEN-LAST:event_botonGrabarClienteActionPerformed

    private void botonConsultarRegistros_FicheroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarRegistros_FicheroClientesActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaResultados_FicheroClientes.getModel();
        
        ArrayList<ObjetoCliente> listaClientes = CONECTORES.obtenerArrayListClientes();
        Iterator<ObjetoCliente> iterador = listaClientes.iterator();
        
        while (iterador.hasNext()) {

            ObjetoCliente fila = iterador.next();
            
        modelo.addRow(new Object[] {fila.getNIF(), fila.getNombre(), fila.getApellidos(), fila.getDomicilio(), fila.getCodigo_Postal(), fila.getPoblacion(), fila.getProvincia(), fila.getTelefono(), fila.getEmail()});
            
        //Debug
//        System.out.println(fila.getNombre());
            
        }
    }//GEN-LAST:event_botonConsultarRegistros_FicheroClientesActionPerformed

    private void tablaResultados_FicheroClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaResultados_FicheroClientesMouseClicked
        ObjetoCliente clienteSeleccionado;
        int filaSeleccionada = tablaResultados_FicheroClientes.getSelectedRow();
        
        String[] datosFila = new String [9];
        for (int i = 0; i < tablaResultados_FicheroClientes.getColumnCount(); i++) {
            datosFila[i] = (String) tablaResultados_FicheroClientes.getModel().getValueAt(filaSeleccionada, i);
        }
        
        clienteSeleccionado = new ObjetoCliente(datosFila[0], datosFila[1], datosFila[2], datosFila[3], datosFila[4], datosFila[5], datosFila[6], datosFila[7], datosFila[8]);
        
        textboxNIF_GestionClientes.setText(clienteSeleccionado.getNIF());
        textboxNombre_GestionClientes.setText(clienteSeleccionado.getNombre());
        textboxApellidos_GestionClientes.setText(clienteSeleccionado.getApellidos());
        textboxDireccion_GestionClientes.setText(clienteSeleccionado.getDomicilio());
        textboxCodPostal_GestionClientes.setText(clienteSeleccionado.getCodigo_Postal());
        textboxPoblacion_GestionClientes.setText(clienteSeleccionado.getPoblacion());
        textboxProvincia_GestionClientes.setText(clienteSeleccionado.getProvincia());
        textboxTelefono_GestionClientes.setText(clienteSeleccionado.getTelefono());
        textboxEmail_GestionClientes.setText(clienteSeleccionado.getEmail());
        

    }//GEN-LAST:event_tablaResultados_FicheroClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FicheroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FicheroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FicheroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FicheroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FicheroClientes dialog = new FicheroClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarRegistros_FicheroClientes;
    private javax.swing.JButton botonGrabarCliente;
    private javax.swing.JButton botonNuevoCliente_GestionClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelApellidos_GestionClientes;
    private javax.swing.JLabel labelCodigoPostal_GestionClientes;
    private javax.swing.JLabel labelDireccion_GestionClientes;
    private javax.swing.JLabel labelEmail_GestionClientes;
    private javax.swing.JLabel labelNIF_GestionCliente;
    private javax.swing.JLabel labelNombre_GestionClientes;
    private javax.swing.JLabel labelPoblacion_GestionClientes;
    private javax.swing.JLabel labelProvincia_GestionClientes;
    private javax.swing.JLabel labelTelefono_GestionClientes;
    private javax.swing.JPanel panelBanner_FicheroClientes;
    private javax.swing.JPanel panelControl_FicheroClientes;
    private javax.swing.JPanel panelDatosCliente_FicheroClientes;
    private javax.swing.JPanel panelPrincipalVentana_FicheroClientes;
    private javax.swing.JTable tablaResultados_FicheroClientes;
    private javax.swing.JTextField textboxApellidos_GestionClientes;
    private javax.swing.JTextField textboxCodPostal_GestionClientes;
    private javax.swing.JTextField textboxDireccion_GestionClientes;
    private javax.swing.JTextField textboxEmail_GestionClientes;
    private javax.swing.JTextField textboxNIF_GestionClientes;
    private javax.swing.JTextField textboxNombre_GestionClientes;
    private javax.swing.JTextField textboxPoblacion_GestionClientes;
    private javax.swing.JTextField textboxProvincia_GestionClientes;
    private javax.swing.JTextField textboxTelefono_GestionClientes;
    // End of variables declaration//GEN-END:variables

    private void limpiarCamposFichaClientes() {
        textboxNIF_GestionClientes.setText(null);
        textboxNombre_GestionClientes.setText(null);
        textboxApellidos_GestionClientes.setText(null);
        textboxDireccion_GestionClientes.setText(null);
        textboxCodPostal_GestionClientes.setText(null);
        textboxPoblacion_GestionClientes.setText(null);
        textboxProvincia_GestionClientes.setText(null);        
        textboxTelefono_GestionClientes.setText(null);
        textboxEmail_GestionClientes.setText(null);

    }
}
