/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author iGimenezSan
 */
public class SolicitudDiagnostico extends javax.swing.JDialog {

    String rutaImagen = "/Impresion/membrete.gif";
    URL url = this.getClass().getResource(rutaImagen);
    ImageIcon icon = new ImageIcon(url);
    
    
    /**
     * Creates new form FicheroReparaciones
     */
    public SolicitudDiagnostico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalVentana_FicheroReparaciones = new javax.swing.JPanel();
        panelBanner_FicheroReparaciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDatosCliente_FicheroReparaciones = new javax.swing.JPanel();
        labelTituloCliente_FicheroReparaciones = new javax.swing.JLabel();
        botonBuscarCliente_FicheroReparaciones = new javax.swing.JButton();
        labelNIF_FicheroReparaciones = new javax.swing.JLabel();
        textboxNIF_FicheroReparaciones = new javax.swing.JTextField();
        labelNombre_FicheroReparaciones = new javax.swing.JLabel();
        textboxNombre_FicheroReparaciones = new javax.swing.JTextField();
        labelApelidos_FicheroReparaciones = new javax.swing.JLabel();
        textboxApellidos_FicheroReparaciones = new javax.swing.JTextField();
        labelDireccion_FicheroReparaciones = new javax.swing.JLabel();
        textboxDireccion_FicheroReparaciones = new javax.swing.JTextField();
        labeCodPostal_FicheroReparaciones = new javax.swing.JLabel();
        textboxCodPostal_FicheroReparaciones = new javax.swing.JTextField();
        labelPoblacion_FicheroReparaciones = new javax.swing.JLabel();
        textboxPoblacion_FicheroReparaciones = new javax.swing.JTextField();
        labelProvincia_FicheroReparaciones = new javax.swing.JLabel();
        textboxProvincia_FicheroReparaciones = new javax.swing.JTextField();
        labelTelefono_FicheroReparaciones = new javax.swing.JLabel();
        textboxTelefono_FicheroReparaciones = new javax.swing.JTextField();
        labelEmail_FicheroReparaciones = new javax.swing.JLabel();
        textboxEmail_FicheroReparaciones = new javax.swing.JTextField();
        panelDatosEquipo_FicheroReparaciones = new javax.swing.JPanel();
        labelTituloEquipo_FicheroReparaciones = new javax.swing.JLabel();
        botonBuscarEquipo_FicheroReparaciones = new javax.swing.JButton();
        labelTipoEquipo_FicheroReparaciones = new javax.swing.JLabel();
        textboxTipoEquipo_FicheroReparaciones = new javax.swing.JTextField();
        labelMarca_FicheroReparaciones = new javax.swing.JLabel();
        textboxMarca_FicheroReparaciones = new javax.swing.JTextField();
        labelModelo_FicheroReparaciones = new javax.swing.JLabel();
        textboxModelo_FicheroReparaciones = new javax.swing.JTextField();
        labeSerialEquipo_FicheroReparaciones = new javax.swing.JLabel();
        textboxSerialEquipo_FicheroReparaciones = new javax.swing.JTextField();
        labelSistema_FicheroReparaciones = new javax.swing.JLabel();
        textboxSistema_FicheroReparaciones = new javax.swing.JTextField();
        labelSerialSistema_FicheroReparaciones = new javax.swing.JLabel();
        textboxSerialSistemalabelSerialSistema_FicheroReparaciones = new javax.swing.JTextField();
        panelDatosReparacionlabelSerialSistema_FicheroReparaciones = new javax.swing.JPanel();
        labelTituloReparacionlabelSerialSistema_FicheroReparaciones = new javax.swing.JLabel();
        labelNumReparacion_FicheroReparaciones = new javax.swing.JLabel();
        textboxNumReparacion_FicheroReparaciones = new javax.swing.JTextField();
        labelFecha_FicheroReparaciones = new javax.swing.JLabel();
        textboxFecha_FicheroReparaciones = new javax.swing.JTextField();
        labelDetalleSintomas_FicheroReparaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areatextSintomas_FicheroReparaciones = new javax.swing.JTextArea();
        labelAccesorios_FicheroReparaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areatextAccesorios = new javax.swing.JTextArea();
        panelControl_FicheroReparaciones = new javax.swing.JPanel();
        BotonNuevaReparacion_FicheroReparaciones = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        String rutaImagen = "/Impresion/membrete.gif";
        URL url = this.getClass().getResource(rutaImagen);
        ImageIcon icon = new ImageIcon(url);
        logotipo = new javax.swing.JLabel("");
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipalVentana_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipalVentana_FicheroReparaciones.setAutoscrolls(true);
        panelPrincipalVentana_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelPrincipalVentana_FicheroReparaciones.setMaximumSize(new java.awt.Dimension(750, 960));
        panelPrincipalVentana_FicheroReparaciones.setMinimumSize(new java.awt.Dimension(750, 960));

        panelBanner_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        panelBanner_FicheroReparaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Solicitud de Diagnóstico");

        javax.swing.GroupLayout panelBanner_FicheroReparacionesLayout = new javax.swing.GroupLayout(panelBanner_FicheroReparaciones);
        panelBanner_FicheroReparaciones.setLayout(panelBanner_FicheroReparacionesLayout);
        panelBanner_FicheroReparacionesLayout.setHorizontalGroup(
            panelBanner_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBanner_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBanner_FicheroReparacionesLayout.setVerticalGroup(
            panelBanner_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBanner_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panelDatosCliente_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosCliente_FicheroReparaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        labelTituloCliente_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloCliente_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTituloCliente_FicheroReparaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloCliente_FicheroReparaciones.setText("Datos de Cliente");

        botonBuscarCliente_FicheroReparaciones.setText("Buscar");
        botonBuscarCliente_FicheroReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarCliente_FicheroReparacionesActionPerformed(evt);
            }
        });
        botonBuscarCliente_FicheroReparaciones.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                botonBuscarCliente_FicheroReparacionesAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        labelNIF_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelNIF_FicheroReparaciones.setText("NIF");

        textboxNIF_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelNombre_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelNombre_FicheroReparaciones.setText("Nombre");

        textboxNombre_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textboxNombre_FicheroReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxNombre_FicheroReparacionesActionPerformed(evt);
            }
        });

        labelApelidos_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelApelidos_FicheroReparaciones.setText("Apellidos");

        textboxApellidos_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelDireccion_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelDireccion_FicheroReparaciones.setText("Dirección");

        textboxDireccion_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labeCodPostal_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labeCodPostal_FicheroReparaciones.setText("C.Postal");

        textboxCodPostal_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textboxCodPostal_FicheroReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxCodPostal_FicheroReparacionesActionPerformed(evt);
            }
        });

        labelPoblacion_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelPoblacion_FicheroReparaciones.setText("Población");

        textboxPoblacion_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelProvincia_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelProvincia_FicheroReparaciones.setText("Provincia");

        textboxProvincia_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textboxProvincia_FicheroReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxProvincia_FicheroReparacionesActionPerformed(evt);
            }
        });

        labelTelefono_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelTelefono_FicheroReparaciones.setText("Teléfono");

        textboxTelefono_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textboxTelefono_FicheroReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxTelefono_FicheroReparacionesActionPerformed(evt);
            }
        });

        labelEmail_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelEmail_FicheroReparaciones.setText("Email");

        textboxEmail_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelDatosCliente_FicheroReparacionesLayout = new javax.swing.GroupLayout(panelDatosCliente_FicheroReparaciones);
        panelDatosCliente_FicheroReparaciones.setLayout(panelDatosCliente_FicheroReparacionesLayout);
        panelDatosCliente_FicheroReparacionesLayout.setHorizontalGroup(
            panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosCliente_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloCliente_FicheroReparaciones)
                    .addGroup(panelDatosCliente_FicheroReparacionesLayout.createSequentialGroup()
                        .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelPoblacion_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(labelApelidos_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelNombre_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDireccion_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTelefono_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelProvincia_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textboxApellidos_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosCliente_FicheroReparacionesLayout.createSequentialGroup()
                                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textboxProvincia_FicheroReparaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(textboxPoblacion_FicheroReparaciones, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(labeCodPostal_FicheroReparaciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textboxCodPostal_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textboxDireccion_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosCliente_FicheroReparacionesLayout.createSequentialGroup()
                                .addComponent(textboxTelefono_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEmail_FicheroReparaciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textboxEmail_FicheroReparaciones))
                            .addGroup(panelDatosCliente_FicheroReparacionesLayout.createSequentialGroup()
                                .addComponent(textboxNombre_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonBuscarCliente_FicheroReparaciones)
                                    .addGroup(panelDatosCliente_FicheroReparacionesLayout.createSequentialGroup()
                                        .addComponent(labelNIF_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textboxNIF_FicheroReparaciones)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosCliente_FicheroReparacionesLayout.setVerticalGroup(
            panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosCliente_FicheroReparacionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloCliente_FicheroReparaciones)
                    .addComponent(botonBuscarCliente_FicheroReparaciones))
                .addGap(18, 18, 18)
                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre_FicheroReparaciones)
                    .addComponent(textboxNombre_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNIF_FicheroReparaciones)
                    .addComponent(textboxNIF_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApelidos_FicheroReparaciones)
                    .addComponent(textboxApellidos_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textboxDireccion_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDireccion_FicheroReparaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPoblacion_FicheroReparaciones)
                    .addComponent(textboxPoblacion_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosCliente_FicheroReparacionesLayout.createSequentialGroup()
                        .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProvincia_FicheroReparaciones)
                            .addComponent(textboxProvincia_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelefono_FicheroReparaciones)
                            .addComponent(textboxTelefono_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail_FicheroReparaciones)
                            .addComponent(textboxEmail_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosCliente_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labeCodPostal_FicheroReparaciones)
                        .addComponent(textboxCodPostal_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosEquipo_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosEquipo_FicheroReparaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        labelTituloEquipo_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloEquipo_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTituloEquipo_FicheroReparaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloEquipo_FicheroReparaciones.setText("Datos Equipo");

        botonBuscarEquipo_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botonBuscarEquipo_FicheroReparaciones.setText("Buscar");
        botonBuscarEquipo_FicheroReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarEquipo_FicheroReparacionesActionPerformed(evt);
            }
        });

        labelTipoEquipo_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelTipoEquipo_FicheroReparaciones.setText("Tipo de Equipo");

        textboxTipoEquipo_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelMarca_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelMarca_FicheroReparaciones.setText("Marca");

        textboxMarca_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelModelo_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelModelo_FicheroReparaciones.setText("Modelo");

        textboxModelo_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labeSerialEquipo_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labeSerialEquipo_FicheroReparaciones.setText("Nº Serie Equipo");

        textboxSerialEquipo_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textboxSerialEquipo_FicheroReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxSerialEquipo_FicheroReparacionesActionPerformed(evt);
            }
        });

        labelSistema_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelSistema_FicheroReparaciones.setText("Sistema Operativo");

        textboxSistema_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelSerialSistema_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelSerialSistema_FicheroReparaciones.setText("Serial S.O.");

        textboxSerialSistemalabelSerialSistema_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelDatosEquipo_FicheroReparacionesLayout = new javax.swing.GroupLayout(panelDatosEquipo_FicheroReparaciones);
        panelDatosEquipo_FicheroReparaciones.setLayout(panelDatosEquipo_FicheroReparacionesLayout);
        panelDatosEquipo_FicheroReparacionesLayout.setHorizontalGroup(
            panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createSequentialGroup()
                        .addComponent(labelSistema_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textboxSistema_FicheroReparaciones))
                    .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createSequentialGroup()
                        .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createSequentialGroup()
                                .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMarca_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textboxMarca_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createSequentialGroup()
                                            .addComponent(labelTipoEquipo_FicheroReparaciones)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textboxTipoEquipo_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(labelModelo_FicheroReparaciones))
                            .addComponent(labelTituloEquipo_FicheroReparaciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBuscarEquipo_FicheroReparaciones)
                            .addComponent(textboxModelo_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createSequentialGroup()
                        .addComponent(labeSerialEquipo_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textboxSerialEquipo_FicheroReparaciones))
                    .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createSequentialGroup()
                        .addComponent(labelSerialSistema_FicheroReparaciones)
                        .addGap(18, 18, 18)
                        .addComponent(textboxSerialSistemalabelSerialSistema_FicheroReparaciones)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosEquipo_FicheroReparacionesLayout.setVerticalGroup(
            panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloEquipo_FicheroReparaciones)
                    .addComponent(botonBuscarEquipo_FicheroReparaciones))
                .addGap(18, 18, 18)
                .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoEquipo_FicheroReparaciones)
                    .addComponent(textboxTipoEquipo_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMarca_FicheroReparaciones)
                    .addComponent(textboxMarca_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModelo_FicheroReparaciones)
                    .addComponent(textboxModelo_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSistema_FicheroReparaciones)
                    .addComponent(textboxSistema_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeSerialEquipo_FicheroReparaciones)
                    .addComponent(textboxSerialEquipo_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosEquipo_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSerialSistema_FicheroReparaciones)
                    .addComponent(textboxSerialSistemalabelSerialSistema_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDatosReparacionlabelSerialSistema_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        panelDatosReparacionlabelSerialSistema_FicheroReparaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        labelTituloReparacionlabelSerialSistema_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));
        labelTituloReparacionlabelSerialSistema_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTituloReparacionlabelSerialSistema_FicheroReparaciones.setText("Datos de Reparación");

        labelNumReparacion_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelNumReparacion_FicheroReparaciones.setText("Nº Reparación");

        textboxNumReparacion_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelFecha_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelFecha_FicheroReparaciones.setText("Fecha");

        textboxFecha_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        labelDetalleSintomas_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelDetalleSintomas_FicheroReparaciones.setText("Detalle de los síntomas");

        areatextSintomas_FicheroReparaciones.setColumns(20);
        areatextSintomas_FicheroReparaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        areatextSintomas_FicheroReparaciones.setRows(5);
        jScrollPane1.setViewportView(areatextSintomas_FicheroReparaciones);

        labelAccesorios_FicheroReparaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelAccesorios_FicheroReparaciones.setText("Accesorios entregados");

        areatextAccesorios.setColumns(20);
        areatextAccesorios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        areatextAccesorios.setRows(5);
        jScrollPane2.setViewportView(areatextAccesorios);

        javax.swing.GroupLayout panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout = new javax.swing.GroupLayout(panelDatosReparacionlabelSerialSistema_FicheroReparaciones);
        panelDatosReparacionlabelSerialSistema_FicheroReparaciones.setLayout(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout);
        panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.setHorizontalGroup(
            panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloReparacionlabelSerialSistema_FicheroReparaciones)
                .addContainerGap(454, Short.MAX_VALUE))
            .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createSequentialGroup()
                            .addComponent(labelNumReparacion_FicheroReparaciones)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textboxNumReparacion_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(labelFecha_FicheroReparaciones)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textboxFecha_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 239, Short.MAX_VALUE))
                        .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createSequentialGroup()
                            .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelDetalleSintomas_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAccesorios_FicheroReparaciones))
                            .addGap(32, 32, 32)
                            .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))))
                    .addGap(20, 20, 20)))
        );
        panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.setVerticalGroup(
            panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloReparacionlabelSerialSistema_FicheroReparaciones)
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNumReparacion_FicheroReparaciones)
                        .addComponent(textboxNumReparacion_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelFecha_FicheroReparaciones)
                        .addComponent(textboxFecha_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelDetalleSintomas_FicheroReparaciones)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDatosReparacionlabelSerialSistema_FicheroReparacionesLayout.createSequentialGroup()
                            .addComponent(labelAccesorios_FicheroReparaciones)
                            .addGap(0, 52, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        panelControl_FicheroReparaciones.setBackground(new java.awt.Color(255, 255, 255));

        BotonNuevaReparacion_FicheroReparaciones.setText("Nueva Reparación");
        BotonNuevaReparacion_FicheroReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevaReparacion_FicheroReparacionesActionPerformed(evt);
            }
        });

        jButton5.setText("Grabar Reparación");

        jButton1.setText("Imprimir Solicitud");

        javax.swing.GroupLayout panelControl_FicheroReparacionesLayout = new javax.swing.GroupLayout(panelControl_FicheroReparaciones);
        panelControl_FicheroReparaciones.setLayout(panelControl_FicheroReparacionesLayout);
        panelControl_FicheroReparacionesLayout.setHorizontalGroup(
            panelControl_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControl_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControl_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonNuevaReparacion_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelControl_FicheroReparacionesLayout.setVerticalGroup(
            panelControl_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControl_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonNuevaReparacion_FicheroReparaciones)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jPanel1.setMaximumSize(new java.awt.Dimension(360, 190));
        jPanel1.setMinimumSize(new java.awt.Dimension(360, 190));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 190));

        logotipo.setIcon(icon);
        logotipo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Condiciones del Servicio");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Isaac Giménez Sánchez");

        jLabel4.setText("C/ Rosellón, 338 Local 4");

        jLabel5.setText("08025 Barcelona (Barcelona)");

        jLabel6.setText("Tlfno. 931743877 / 640341275");

        jLabel7.setText("isaacgimenez@gmail.com");

        jLabel8.setText("NIF. 46351946T");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalVentana_FicheroReparacionesLayout = new javax.swing.GroupLayout(panelPrincipalVentana_FicheroReparaciones);
        panelPrincipalVentana_FicheroReparaciones.setLayout(panelPrincipalVentana_FicheroReparacionesLayout);
        panelPrincipalVentana_FicheroReparacionesLayout.setHorizontalGroup(
            panelPrincipalVentana_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(panelBanner_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createSequentialGroup()
                            .addComponent(panelDatosCliente_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(panelDatosEquipo_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createSequentialGroup()
                            .addComponent(panelDatosReparacionlabelSerialSistema_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(panelControl_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalVentana_FicheroReparacionesLayout.setVerticalGroup(
            panelPrincipalVentana_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createSequentialGroup()
                        .addComponent(panelBanner_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDatosCliente_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosEquipo_FicheroReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalVentana_FicheroReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatosReparacionlabelSerialSistema_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelControl_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipalVentana_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipalVentana_FicheroReparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textboxNombre_FicheroReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxNombre_FicheroReparacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxNombre_FicheroReparacionesActionPerformed

    private void botonBuscarCliente_FicheroReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarCliente_FicheroReparacionesActionPerformed
        FicheroClientes ventana = new FicheroClientes(null, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_botonBuscarCliente_FicheroReparacionesActionPerformed

    private void botonBuscarEquipo_FicheroReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarEquipo_FicheroReparacionesActionPerformed
        FicheroEquipos ventana = new FicheroEquipos(null, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_botonBuscarEquipo_FicheroReparacionesActionPerformed

    private void textboxSerialEquipo_FicheroReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxSerialEquipo_FicheroReparacionesActionPerformed

    }//GEN-LAST:event_textboxSerialEquipo_FicheroReparacionesActionPerformed

    private void textboxCodPostal_FicheroReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxCodPostal_FicheroReparacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxCodPostal_FicheroReparacionesActionPerformed

    private void textboxProvincia_FicheroReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxProvincia_FicheroReparacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxProvincia_FicheroReparacionesActionPerformed

    private void textboxTelefono_FicheroReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxTelefono_FicheroReparacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxTelefono_FicheroReparacionesActionPerformed

    private void BotonNuevaReparacion_FicheroReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevaReparacion_FicheroReparacionesActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_BotonNuevaReparacion_FicheroReparacionesActionPerformed

    private void botonBuscarCliente_FicheroReparacionesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_botonBuscarCliente_FicheroReparacionesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarCliente_FicheroReparacionesAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitudDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitudDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitudDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitudDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SolicitudDiagnostico dialog = new SolicitudDiagnostico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonNuevaReparacion_FicheroReparaciones;
    private javax.swing.JTextArea areatextAccesorios;
    private javax.swing.JTextArea areatextSintomas_FicheroReparaciones;
    private javax.swing.JButton botonBuscarCliente_FicheroReparaciones;
    private javax.swing.JButton botonBuscarEquipo_FicheroReparaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labeCodPostal_FicheroReparaciones;
    private javax.swing.JLabel labeSerialEquipo_FicheroReparaciones;
    private javax.swing.JLabel labelAccesorios_FicheroReparaciones;
    private javax.swing.JLabel labelApelidos_FicheroReparaciones;
    private javax.swing.JLabel labelDetalleSintomas_FicheroReparaciones;
    private javax.swing.JLabel labelDireccion_FicheroReparaciones;
    private javax.swing.JLabel labelEmail_FicheroReparaciones;
    private javax.swing.JLabel labelFecha_FicheroReparaciones;
    private javax.swing.JLabel labelMarca_FicheroReparaciones;
    private javax.swing.JLabel labelModelo_FicheroReparaciones;
    private javax.swing.JLabel labelNIF_FicheroReparaciones;
    private javax.swing.JLabel labelNombre_FicheroReparaciones;
    private javax.swing.JLabel labelNumReparacion_FicheroReparaciones;
    private javax.swing.JLabel labelPoblacion_FicheroReparaciones;
    private javax.swing.JLabel labelProvincia_FicheroReparaciones;
    private javax.swing.JLabel labelSerialSistema_FicheroReparaciones;
    private javax.swing.JLabel labelSistema_FicheroReparaciones;
    private javax.swing.JLabel labelTelefono_FicheroReparaciones;
    private javax.swing.JLabel labelTipoEquipo_FicheroReparaciones;
    private javax.swing.JLabel labelTituloCliente_FicheroReparaciones;
    private javax.swing.JLabel labelTituloEquipo_FicheroReparaciones;
    private javax.swing.JLabel labelTituloReparacionlabelSerialSistema_FicheroReparaciones;
    private javax.swing.JLabel logotipo;
    private javax.swing.JPanel panelBanner_FicheroReparaciones;
    private javax.swing.JPanel panelControl_FicheroReparaciones;
    private javax.swing.JPanel panelDatosCliente_FicheroReparaciones;
    private javax.swing.JPanel panelDatosEquipo_FicheroReparaciones;
    private javax.swing.JPanel panelDatosReparacionlabelSerialSistema_FicheroReparaciones;
    private javax.swing.JPanel panelPrincipalVentana_FicheroReparaciones;
    private javax.swing.JTextField textboxApellidos_FicheroReparaciones;
    private javax.swing.JTextField textboxCodPostal_FicheroReparaciones;
    private javax.swing.JTextField textboxDireccion_FicheroReparaciones;
    private javax.swing.JTextField textboxEmail_FicheroReparaciones;
    private javax.swing.JTextField textboxFecha_FicheroReparaciones;
    private javax.swing.JTextField textboxMarca_FicheroReparaciones;
    private javax.swing.JTextField textboxModelo_FicheroReparaciones;
    private javax.swing.JTextField textboxNIF_FicheroReparaciones;
    private javax.swing.JTextField textboxNombre_FicheroReparaciones;
    private javax.swing.JTextField textboxNumReparacion_FicheroReparaciones;
    private javax.swing.JTextField textboxPoblacion_FicheroReparaciones;
    private javax.swing.JTextField textboxProvincia_FicheroReparaciones;
    private javax.swing.JTextField textboxSerialEquipo_FicheroReparaciones;
    private javax.swing.JTextField textboxSerialSistemalabelSerialSistema_FicheroReparaciones;
    private javax.swing.JTextField textboxSistema_FicheroReparaciones;
    private javax.swing.JTextField textboxTelefono_FicheroReparaciones;
    private javax.swing.JTextField textboxTipoEquipo_FicheroReparaciones;
    // End of variables declaration//GEN-END:variables

    private void limpiarFormulario() {
        
        // Panel datos cliente
        textboxNombre_FicheroReparaciones.setText(null);
        textboxApellidos_FicheroReparaciones.setText(null);
        textboxNIF_FicheroReparaciones.setText(null);
        textboxDireccion_FicheroReparaciones.setText(null);
        textboxCodPostal_FicheroReparaciones.setText(null);
        textboxPoblacion_FicheroReparaciones.setText(null);
        textboxProvincia_FicheroReparaciones.setText(null);
        textboxTelefono_FicheroReparaciones.setText(null);
        textboxEmail_FicheroReparaciones.setText(null);
        
        // Panel datos equipo
        textboxTipoEquipo_FicheroReparaciones.setText(null);
        textboxMarca_FicheroReparaciones.setText(null);
        textboxModelo_FicheroReparaciones.setText(null);
        textboxSerialEquipo_FicheroReparaciones.setText(null);
        textboxSistema_FicheroReparaciones.setText(null);
        textboxSerialSistemalabelSerialSistema_FicheroReparaciones.setText(null);
        
        // Panel datos reparacion
        textboxNumReparacion_FicheroReparaciones.setText(null);
        textboxFecha_FicheroReparaciones.setText(null);
        areatextSintomas_FicheroReparaciones.setText(null);
        areatextAccesorios.setText(null);
    }
}